name: Build
on:
  pull_request:
  push:
    branches: [main]
jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    env:
      CI: true
    steps:
      - name: Get the code
        uses: actions/checkout@v2
      - name: Setup NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Cache npm modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.OS }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-node-
      - name: Install npm modules
        run: npm i
      - run: npm run test:lint
  unit-test:
    name: unit test
    runs-on: ubuntu-latest
    env:
      CI: true
    steps:
      - name: Get the code
        uses: actions/checkout@v2
      - name: Setup NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Install npm modules
        run: npm i
      - run: npm run test:unit
  build:
    name: Build & Bundle
    runs-on: ubuntu-latest
    env:
      CI: true
    steps:
      - name: Get the code
        uses: actions/checkout@v2
      - name: Setup NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Install npm modules
        run: npm i
      - run: npm run build
