name: Release a new version
on:
  push:
    tags: 'v*'
jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    env:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    steps:
      - name: Get the code
        uses: actions/checkout@v2
      - name: Install NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          registry-url: 'https://registry.npmjs.org'
      - name: Cache npm modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.OS }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-node-
      - name: Install npm modules
        run: npm i
      - name: Publish to NPM
        run: npm publish --tag next --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Calculate version
        id: get_version
        run: |
          echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
          echo ::set-output name=VERSION_WITHOUT_V::${GITHUB_REF/refs\/tags\/v/}
      - name: Notify Slack
        uses: pullreminders/slack-action@master
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        with:
          args: '{\"channel\":\"CQ9AG10AC\",\"text\":\":rocket: ${{ steps.get_version.outputs.VERSION }} of Pebble-Formik has been released!\nSee it on <https://www.npmjs.com/package/@istreamplanet/pebble-formik/v/${{ steps.get_version.outputs.VERSION_WITHOUT_V }}|NPM>\"}'
